FROM alpine:3.22
RUN apk add --no-cache aria2
COPY scripts/download-dump.sh /usr/local/bin/download-dump.sh
RUN chmod +x /usr/local/bin/download-dump.sh
WORKDIR /data/dumps
ENTRYPOINT ["/usr/local/bin/download-dump.sh"]
